### ISSUE TITLE
Gradle Assembly Errors

### ISSUE THREAD

**Issue by rmurphy2718** [dccspeed/fractal#1]
[install_fractal_rmurphy.log](https://github.com/dccspeed/fractal/files/3596605/install_fractal_rmurphy.log)
I had some problems installing, specifically, running `gradlew assemble ` on a Linux machine.  I have attached the log file.

I was advised that the installation is assuming a build with Java 8 whereas the machine was using Java 11.  Exporting `JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64` allowed the build to complete.  Please let me know if you need more details.

**Comment by viniciusvdias** [comment]
Yes, this is exactly right, currently we support only java 8 version. I will make sure the documentation is corrected. Thanks for pointing out.

Let me know if you have any more issues with the compilation.
