### ISSUE TITLE
Matching a custom pattern

### ISSUE THREAD

**Issue by jplozi** [dccspeed/fractal#16]
Hi all,

I'm currently experimenting with Fractal. I've been able to get the right count (28769868) when matching triangles in the following graph: [https://snap.stanford.edu/data/as-Skitter.html](https://snap.stanford.edu/data/as-Skitter.html) (I had to reformat the file). The execution took around 28 minutes on a 9-node cluster of machines with 56 hardware threads and 768GB of RAM each, and an Infiniband connection (does that execution time sound reasonable to you?). I'm now trying to match the following pattern, which comes from the G-Miner EuroSys '18 paper:

![Screenshot from 2020-04-07 22-53-57](https://user-images.githubusercontent.com/17784062/78806294-c2616300-79c2-11ea-9f2d-c6dfefe1033a.png)

I replaced labels a, b, c, and d with 0, 1, 2, and 3 respectively, and I'm trying to match the pattern in the Skitter graph in which I added random labels between 0 and 6. I created a file, `data/p-pattern.graph`, with these contents:
```
0 0 1 2
1 1 0 2
2 2 0 1 3
3 1 2
4 4 3
```

I'm running the benchmark with:

`spark_master=... steps=4 inputgraph=~/fractal/formatted_data/fractal.out.as-skitter master_memory=700g worker_memory=700g num_workers=8 worker_cores=56 log_level=warn app=gquerying query=$FRACTAL_HOME/data/p-pattern.graph ./bin/fractal.sh`

I'm getting a crash however:
```
20/04/07 11:40:56 WARN scheduler.TaskSetManager: Lost task 215.0 in stage 1.0 (TID 663, 10.149.0.23, executor 7): java.lang.ArrayIndexOutOfBoundsException: 4
    at br.ufmg.cs.systems.fractal.util.collection.ObjArrayList.get(ObjArrayList.java:438)
    at br.ufmg.cs.systems.fractal.pattern.BasicPattern.sbLowerBound(BasicPattern.java:535)
    at br.ufmg.cs.systems.fractal.subgraph.PatternInducedSubgraph.updateExtensions(PatternInducedSubgraph.java:227)
    at br.ufmg.cs.systems.fractal.subgraph.BasicSubgraph.computeExtensions(BasicSubgraph.java:178)
    at br.ufmg.cs.systems.fractal.computation.SubgraphEnumerator.computeExtensions(SubgraphEnumerator.java:75)
    at br.ufmg.cs.systems.fractal.computation.BasicComputation.expandCompute(BasicComputation.java:120)
    ...
```

Which made me wonder if using `steps=4` is correct, but given that the pattern is of size 5, I believe it is. Do you have any idea what could be happening?

PS: I'm also getting the warning below whatever I run and I'm wondering if I should just ignore it.
`[WARN] [SECURITY][04/07/2020 11:40:55.991] [fractal-msgsys-akka.actor.default-dispatcher-3] [akka.serialization.Serialization(akka://fractal-msgsys)] Using the default Java serializer for class [br.ufmg.cs.systems.fractal.computation.HelloSlave] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'`

**Comment by viniciusvdias** [comment]
Hi Jean, thank you for your interest,

I think this should be an easy fix, so there you go:

1. Looks like your pattern is disconnected and we do not support that. If you want the same pattern as the picture, vertex 3 (with label 1 or b) should be connected also to vertex 4 (with label 4 or d). That makes sense?

2. About the step=4, this is actually correct: the number of vertex we should add to a single-vertex subgraph. In other words, the number of vertex in the pattern minus one.

3. About the warning: totally expected. Fractal uses the default java serializer at the moment.
If the error still persists, we ask you to please create an issue in the project github page, so we can have a better control on how to fix it.

**Comment by jplozi** [comment]
I see, that makes sense. Thanks a lot!

**Comment by viniciusvdias** [comment]
The following query graph should fix this:

```
0 0 1 2
1 1 0 2
2 2 0 1 3
3 1 2 4
4 4 3
```
