### ISSUE TITLE
Another entry possible for several graphs

### ISSUE THREAD

**Issue by vle123** [dccspeed/fractal#21]
hi Fractal,

I'm coming for a question on the input graph. I wanted to know if it was possible to put in input several graphs separated by a stop mark, so that each vertex of the different graph starts from 0. From what I'm seeing, the numbering of the first vertex of the second graph begins by incrementing the last vertex id of the first graph. So I wanted to know if there was a way to make an entry like this?

**Comment by viniciusvdias** [comment]
At this moment, Fractal expects a single graph as input. I would suggest creating an external mapping between node IDs in the original collection of graphs into node IDs of a single graph. This is a workaround solution, while this is not implemented.

I will keep this open anyway.

Thanks.
