### ISSUE TITLE
Isomorphism problem with edge labels

### ISSUE THREAD

**Issue by vle123** [dccspeed/fractal#22]
hi, I have a problem with graphs with edges labels. The problem is that some patterns which are isomorphic are not group. I put an example with a small graph. I would like to know if there is a manipulation that I couldn't find to resolve it.

for a graph:
-
0 0 1 2 2 4
1 1 2 3 
2 0 
3 0 4 3 5 4
4 1 5 2
5 0
-
I have as a result
-
[(0,0),(4)-(1,0)],[(1,0),(3)-(2,1)],[(0,0),(2)-(2,1)] count 1 
[(0,0),(4)-(1,0)],[(1,0),(2)-(2,1)],[(0,0),(3)-(2,1)] count 1
-

the two patterns are isomorphic, is it possible to have the same result but with only one pattern for this example?

**Comment by viniciusvdias** [comment]
Hi,

This functionality is not yet fully integrated. Can you provide more info about the code you are running and execution parameters so I can reproduce it?

**Comment by vle123** [comment]
I found this problem on my charts but the problem occurs on the small example I showed above. For this I am using the basic code specifying that it was a graphic with edge labels. I join the code and the input graph

[code.txt](https://github.com/dccspeed/fractal/files/6005617/code.txt)
[graph.txt](https://github.com/dccspeed/fractal/files/6005618/graph.txt)

**Comment by viniciusvdias** [comment]
Ok, I think I got it. JBlissPattern does not support labels on edges, we have VICPatterns for that. It works for induced subgraphs.

```
package br.ufmg.cs.systems.fractal.apps

import br.ufmg.cs.systems.fractal._
import br.ufmg.cs.systems.fractal.pattern.Pattern
import br.ufmg.cs.systems.fractal.util.Logging
import org.apache.hadoop.io.LongWritable
import org.apache.spark.{SparkConf, SparkContext}

object EdgeLabeledMotifsApp extends Logging {
  def main(args: Array[String]): Unit = {
    // environment setup
    val conf = new SparkConf().setAppName("MyMotifsApp")
    val sc = new SparkContext(conf)
    val fc = new FractalContext(sc)
    val graphPath = args(0) // input graph
    val fgraph = fc.textFile (graphPath)
    fgraph.set("edge_labelled", true)
    fgraph.set("fractal.pattern.class", "br.ufmg.cs.systems.fractal.pattern.VICPattern")
    val AGG_MOTIFS = "motifs"
    val motifs = fgraph.vfractoid.
      expand(1).
      aggregate [Pattern,LongWritable] (
        AGG_MOTIFS,
        (e,c,k) => { e.getPattern },
        (e,c,v) => { v.set(1); v },
        (v1,v2) => { v1.set(v1.get() + v2.get()); v1 }).
      explore(2)

    val motifsMap = motifs.aggregationMap[Pattern,LongWritable](AGG_MOTIFS)
    for ((motif,count) <- motifsMap) {
      logInfo(s"motif=${motif} count=${count}")
    }
    
    // environment cleaning
    fc.stop()
    sc.stop()
  }
}
```
