### ISSUE TITLE
Can I get graph pattern and all instances of the graph pattern at the same time?

### ISSUE THREAD

**Issue by hououou** [dccspeed/fractal#24]
Hello! I am interested in getting frequent graph pattern and all matches(embeddings/instances) of pattern at same time. It seems that fsm algorithm can get the graph pattern but cannot get the whole matches of the pattern. And gquery can get the whole matches of one pattern. Can I get all frequent graph pattern and matches of pattern at the same time?

**Comment by viniciusvdias** [comment]
Hello! The way I see there is two alternatives: (1) modify [FSM provided application](https://github.com/dccspeed/fractal/blob/779031807077fd8f776ced8de09ddbf6ea831bf1/fractal-core/src/main/scala/br/ufmg/cs/systems/fractal/BuiltInAlgorithms.scala#L65) to output the subgraph instances; or (2) get the output frequent patterns from the provided application and query each one using [pattern matching](https://github.com/dccspeed/fractal/blob/779031807077fd8f776ced8de09ddbf6ea831bf1/fractal-core/src/main/scala/br/ufmg/cs/systems/fractal/BuiltInAlgorithms.scala#L130).
