### ISSUE TITLE
ClassNotFoundException, Jars do not exist, batch example 

### ISSUE THREAD

**Issue by rmurphy2718** [dccspeed/fractal#5]
Dear Fractal,

I tried to run your batch example using cube.graph and ran into a problem. 

I guess the jar does not exist in the fractal build? Thanks.

`steps=2 inputgraph=$FRACTAL_HOME/data/cube.graph alg=cliques ./bin/fractal.sh
`
I got this output

> FRACTAL_HOME is set to /home/murph213/Downloads/Installers/fractal
> 
> SPARK_HOME is set to /usr/local/spark
> alg is set to 'cliques'
> inputgraph is set to '/home/murph213/Downloads/Installers/fractal/data/cube.graph'
> steps is set to '2'
> spark-submit --master local[1] --deploy-mode client \ --driver-memory 2g \ --num-executors 1 \ --executor-cores 1 \ --executor-memory 2g \ --class br.ufmg.cs.systems.fractal.FractalSparkRunner \ --jars /home/murph213/Downloads/Installers/fractal/build/libs/fractal-SPARK-2.2.0-all.jar \ /home/murph213/Downloads/Installers/fractal/build/libs/fractal-SPARK-2.2.0-all.jar \ al /home/murph213/Downloads/Installers/fractal/data/cube.graph cliques scratch 1 2 info
> 19/09/13 12:53:06 WARN Utils: Your hostname, RM-Satellite resolves to a loopback address: 127.0.1.1; using 192.168.2.3 instead (on interface eth0)
> 19/09/13 12:53:06 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
> 19/09/13 12:53:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
> 19/09/13 12:53:07 WARN DependencyUtils: Local jar /home/murph213/Downloads/Installers/fractal/build/libs/fractal-SPARK-2.2.0-all.jar does not exist, skipping.
> 19/09/13 12:53:07 WARN DependencyUtils: Local jar /home/murph213/Downloads/Installers/fractal/build/libs/fractal-SPARK-2.2.0-all.jar does not exist, skipping.
> 19/09/13 12:53:07 WARN SparkSubmit$$anon$2: Failed to load br.ufmg.cs.systems.fractal.FractalSparkRunner.
> java.lang.ClassNotFoundException: br.ufmg.cs.systems.fractal.FractalSparkRunner
> at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> at java.lang.Class.forName0(Native Method)
> at java.lang.Class.forName(Class.java:348)
> at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
> at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:806)
> at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
> at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
> at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
> at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
> at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
> at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> 19/09/13 12:53:07 INFO ShutdownHookManager: Shutdown hook called
> 19/09/13 12:53:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-b89a1b4f-b7a3-4ade-a289-7b78d2d92c22
>

**Comment by viniciusvdias** [comment]
Very strange, it looks like your jar is missing.
```
WARN DependencyUtils: Local jar /home/murph213/Downloads/Installers/fractal/build/libs/fractal-SPARK-2.2.0-all.jar does not exist, skipping.
```

Can you double check that `/home/murph213/Downloads/Installers/fractal/build/libs/fractal-SPARK-2.2.0-all.jar` exists in your local file system?

As far as I understood this is a local execution, right?

**Comment by rmurphy2718** [comment]
Yes, it is local (for now).  My build seems to be working now that I've cloned your updated branch, which was mentioned in another conversation thread.
