### ISSUE TITLE
Problem running sample batch example locally, Error message: No computation is set

### ISSUE THREAD

**Issue by rmurphy2718** [dccspeed/fractal#7]
Hi Fractal,

I have successfully built using gradlew.  I am using Ubuntu 16.04, where I have a Spark Cluster running.  I have attached the Spark monitor view.

I ran
`steps=2 inputgraph=$FRACTAL_HOME/data/citeseer-single-label.graph alg=cliques ./bin/fractal.sh`
and got the error

> Error message: No computation is set

The full log is attached
[first_batch_test.log](https://github.com/dccspeed/fractal/files/3612914/first_batch_test.log)

Please advise, and thanks so much!
--Ryan Murphy

![image](https://user-images.githubusercontent.com/15987518/64910787-711d1980-d6e8-11e9-878a-c968578592eb.png)

**Comment by viniciusvdias** [comment]
This one I can't figure out just yet, but I am pretty sure this message is a warning and should not lead to this crash. Clearly this message should be revised. Can you try the hints I posted on #8 to see if it helps?

**Comment by rmurphy2718** [comment]
Thanks so much for your fast replies and willingness to help.

I am not sure how to figure out the URL to spark master on a remote (#8 ), so I am following your hints locally.

(1) I appended my spark_master to the beginning of the command.  You can see from my screenshot above where I'm getting the URL from.
(2) I tried both accessing files from the "normal filesystem" using file:// and putting my data inside the HDFS.  They both gave the same result

`spark_master=spark://RM-Satellite:7077 steps=2 inputgraph=$MYDATA alg=cliques ./bin/fractal.sh  > fourth_batch.log 2>&1`

where 
`hdfs dfs -ls $MYDATA`
gives
>-rw-r--r--   1 murph213 murph213      66478 2019-09-14 14:51 /home/murph213/hadoopdir/data/citeseer-single-label.graph

and
`spark_master=spark://RM-Satellite:7077 steps=2 inputgraph=file://$FRACTAL_HOME/data/citeseer-single-label.graph alg=cliques ./bin/fractal.sh  > fifth_batch.log 2>&1`

[fourth_batch.log](https://github.com/dccspeed/fractal/files/3613058/fourth_batch.log)
[fifth_batch.log](https://github.com/dccspeed/fractal/files/3613057/fifth_batch.log)

If you think this shouldn't lead to an error, what is the error causing the crash?  I am not finding any output files so I don't think the program is finishing

**Comment by viniciusvdias** [comment]
Looks like both executions 'fourth' and 'fifth' are fine!
The cliques algorithm actually just lists cliques, with steps=2 you are listing triangles (3 vertices).

Take a look at this line:

```
19/09/14 15:01:00 INFO CliquesApp: CliquesApp comm=scratch numPartitions=1 explorationSteps=2 graph=FractalGraph(file:///home/murph213/Downloads/Installers/vinic_fractal/fractal/data/citeseer-single-label.graph)  numValidSubgraphs=1166 elapsed=24367
```

means that the execution listed 1166 unique triangles from citeseer.

Other built-in applications may return a different output. This is the case of motifs, that returns a mapping of patterns and counts.

**Comment by rmurphy2718** [comment]
Oh great, that is good news.  Thanks for pointing that out to me.
